// This file was generated by the "svnrev" utility
// You should not modify it manually, as it may be re-generated.
//
// $Revision: 209 $
// $Date: 2012-11-30 $
//

#ifndef SVNREV_HPP
#define SVNREV_HPP


#define SVN_REV       209
#define SVN_REVDATE   "2012-11-30"


#endif /* SVNREV_HPP */
